# Generated by Django 5.0.4 on 2024-04-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.GenericIPAddressField(protocol='IPv4')),
                ('status', models.IntegerField(choices=[(0, 'offline'), (1, 'error'), (2, 'online')])),
            ],
        ),
    ]
