# Generated by Django 5.0.4 on 2024-04-24 09:44

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('object', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.IntegerField(choices=[(0, 'waiting'), (1, 'processing'), (2, 'finished'), (3, 'error')], default=0)),
                ('creation_ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_ts', models.DateTimeField(blank=True, null=True)),
                ('verdict', models.IntegerField(choices=[(0, 'malicious'), (1, 'suspicious'), (2, 'clean')])),
            ],
        ),
    ]
