# Generated by Django 5.0.4 on 2024-04-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_analyzer_nodes'),
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzer',
            name='nodes',
            field=models.ManyToManyField(related_name='analyzers', to='node.node'),
        ),
    ]
